export enum TaskType {
  AI_CONTENT_GENERATION = "AI_CONTENT_GENERATION",
  EMAIL_PROCESSING = "EMAIL_PROCESSING",
  DATA_ANALYSIS = "DATA_ANALYSIS",
  FILE_PROCESSING = "FILE_PROCESSING",
  NOTIFICATION_SENDING = "NOTIFICATION_SENDING",
  REPORT_GENERATION = "REPORT_GENERATION",
  CUSTOM = "CUSTOM",
}
